language: python

python:
  - "3.6"

dist: trusty

jdk:
  - openjdk8


install:
  - "pip install -e -q . --upgrade"
  - "pip install -r -q requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
