language: python

python:
  - "3.6"

before_install:
  - java install openjdk8

install:
  - "pip install -e . --upgrade"
  - "pip install -r requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
