language: python

python:
  - "3.6"

dist: trusty

jdk:
  - openjdk8

install:
  - "pip install -e . --upgrade"
  - "pip install --quiet -r requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
