language: python

python:
  - "3.6"

install:
  - "pip install -e . --upgrade"
  - "pip install pipenv"
  - "pipenv install --dev"

script:
  - echo "Running unit tests"
  - "pipenv run nosetests -s -v tests/"
