language: java

jdk:
  - openjdk8

python:
  - "3.6"

install:
  - "pip install -e . --upgrade"
  - "pip install -r requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
