language: python

python:
  - "3.6"

install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y oracle-java8-installer || true
  #todo remove this kludge and the above || true when the ppa is fixed
  - cd /var/lib/dpkg/info
  - sudo apt-get update
  - sudo apt-get install -y oracle-java8-installer
  - cd $TRAVIS_BUILD_DIR
  - "pip install -e . --upgrade"
  - "pip install -r requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
