language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
  - "pip install -e . --upgrade"
  - "pip install -r requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
