language: python

python:
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:openjdk-r/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y openjdk-8-jdk
  - sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
sudo: required

install:
  - "pip install -e . --upgrade"
  - "pip install -r requirements.txt"

script:
  - echo "Running unit tests"
  - "nosetests -s -v tests/"
